import type { InferGetServerSidePropsType, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useContext } from 'react';
import {
	RepositoryContext,
	taskRepository,
} from '../contexts/RepositoryContext';
import { v4 as uuidv4 } from 'uuid';
import styles from '../styles/Home.module.css';

type Props = InferGetServerSidePropsType<typeof getServerSideProps>;

const Home: NextPage<Props> = ({ tasks }) => {
	const { taskRepository } = useContext(RepositoryContext);

	const onSubmit = () => {
		taskRepository.storeTask({
			id: uuidv4(),
			title: 'test',
			description: 'test',
		});
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>

				<p className={styles.description}>
					Get started by editing{' '}
					<code className={styles.code}>pages/index.tsx</code>
				</p>

				<button type="button" onClick={onSubmit}>
					作成
				</button>

				<ul>
					{tasks.map((task) => (
						<li key={task.id}>{task.title}</li>
					))}
				</ul>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;

export const getServerSideProps = async () => {
	const tasks = await taskRepository.getTasks();
	return {
		props: {
			tasks,
		},
	};
};
